'use client';

import { motion } from 'framer-motion';

const sectionVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.8 } },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen aurora-page font-sans px-4 sm:px-6 py-10 sm:py-20">
      <motion.div
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.3 }}
        variants={sectionVariants}
        className="panel max-w-4xl mx-auto space-y-8 sm:space-y-12 p-5 sm:p-8 md:p-10"
      >
        <h3 className="text-3xl sm:text-4xl font-bold text-primary text-center mb-6 sm:mb-12 ">
          Terms of Service
        </h3>

        <section className="space-y-4">
          <p className="text-muted-foreground text-sm sm:text-lg leading-relaxed">
            By using our AI-powered exam platform, you agree to comply with all applicable academic policies, rules, and regulations. Misuse of the platform, including cheating, unauthorized access, or sharing login credentials, is strictly prohibited.
          </p>
          <ul className="list-disc list-inside text-muted-foreground text-sm sm:text-base space-y-2 ml-2 sm:ml-4 leading-relaxed">
            <li>Users must provide accurate personal information.</li>
            <li>The platform reserves the right to suspend or terminate accounts for violations.</li>
            <li>Content generated by the AI is for educational purposes only.</li>
            <li>All intellectual property, including exam content and analytics, belongs to the platform.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl sm:text-3xl font-semibold text-primary border-b border-border pb-2">
            User Responsibilities
          </h2>
          <ul className="list-disc list-inside text-muted-foreground text-sm sm:text-base space-y-2 ml-2 sm:ml-4 leading-relaxed">
            <li>Keep your login credentials confidential.</li>
            <li>Report any suspicious activity or technical issues immediately.</li>
            <li>Follow all exam and platform instructions carefully.</li>
            <li>Respect intellectual property and do not attempt to copy or distribute content.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl sm:text-3xl font-semibold text-primary border-b border-border pb-2">
            Updates & Contact
          </h2>
          <p className="text-muted-foreground text-sm sm:text-lg leading-relaxed">
            These terms may be updated periodically. Users are encouraged to review them regularly. For any questions, contact our support team.
          </p>
        </section>
      </motion.div>
    </main>
  );
}